apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: psoplugins.purestorage.com
spec:
  group: purestorage.com
  names:
    kind: PSOPlugin
    listKind: PSOPluginList
    plural: psoplugins
    singular: psoplugin
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
