apiVersion: apps/v1
kind: Deployment
metadata:
  name: pso-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pso-operator
  template:
    metadata:
      labels:
        name: pso-operator
    spec:
      serviceAccountName: pso-operator
      containers:
        - name: pso-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE 
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pso-operator"
