kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pso-operator
rules:
  - apiGroups:
    - purestorage.com
    resources:
    - "*"
    verbs:
    - "*"
  - apiGroups:
    - ""
    resources:
    - serviceaccounts
    - persistentvolumeclaims
    - persistentvolumes
    - events
    verbs:
    - "*"
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - "*"
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterrolebindings
    verbs:
    - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-pso-operator
subjects:
- kind: ServiceAccount
  name: pso-operator
roleRef:
  kind: ClusterRole
  name: pso-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pso-operator
rules:
  - apiGroups:
    - purestorage.com
    resources:
    - "*"
    verbs:
    - "*"
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - configmaps
    - serviceaccounts
    verbs:
    - "*"
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - "*"
  - apiGroups:
    - extensions
    resources:
    - daemonsets
    verbs:
    - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-pso-operator
subjects:
- kind: ServiceAccount
  name: pso-operator
roleRef:
  kind: Role
  name: pso-operator
  apiGroup: rbac.authorization.k8s.io
