apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pure-provisioner
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pure_k8s_plugin.labels" . | indent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pure-provisioner
  template:
    metadata:
      labels:
        app: pure-provisioner
{{ include "pure_k8s_plugin.labels" . | indent 8}}
    spec:
      serviceAccountName: {{ .Values.clusterrolebinding.serviceAccount.name }}
      containers:
        - name: pure-provisioner
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /k8s-provisioner
            - '-logtostderr=false'
            - '-stderrthreshold=2'
{{- if eq .Values.app.debug true}}
            - '--debug'
{{- end}}
          volumeMounts:
          - name: config
            mountPath: /etc/pure
          env:
          - name: PURE_DISCOVERY_CONF
            value: /etc/pure/pure.json
          - name: PURE_K8S_NAMESPACE
            value: {{ .Values.namespace.pure }}
      volumes:
        - name: config
          configMap:
            name: pure-provisioner-config
